//  Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//  By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

package main

import "fmt"

func evenness(i int32) bool {
	if i%2 == 0 {
		return true
	}
	return false
}

func fibonacci() (sum int32) {
	numbers := [3]int32{1, 2, 0}
	sum = 2
	for {
		numbers[2] = numbers[0] + numbers[1]
		if numbers[2] > 4000000 {
			break
		}
		if evenness(numbers[2]) {
			fmt.Println(numbers[2])
			sum = sum + numbers[2]
		}
		numbers[0] = numbers[1]
		numbers[1] = numbers[2]

	}
	return
}

func main() {
	fmt.Printf("The sum is %v", fibonacci())
}
